### ISSUE TITLE
tracking(`learner`): database upgrades and versioning

### ISSUE THREAD

**Issue by Autoparallel** [Autoparallel/learner#133]
Right now the database is pretty basic. Although it doesn't need to be _crazy_, it could definitely support some more features and allow room to grow in the future. I'm also not an expert on managing databases and migrations so... some learning here for me with SQLite.

## Issues
- [ ] chore/question(`learner`): set up database versioning and migrations/scripts
- [ ] #97 
- [ ] feat(`learner`): add "tags" as a component for paper in database
- [ ] feat/question(`learner`): consider allowing for "resource" as more general than "paper" in database
- [ ] question(`learner`): other useful organizational flows for resources in learner database?
