### ISSUE TITLE
docs(mdbook): create an mdbook for this repository

### ISSUE THREAD

**Issue by Autoparallel** [Autoparallel/learner#46]
## Description
As features increase, having nice documentation will be important. Ideally, the mdbook contains runnable code snippets that are tested before the book is updated/merged into main in a workflow.

No specific outline yet, but putting this out there. 

## Tasks to close
- [ ] Create an mdbook in the root directory.
- [ ] Create a rough outline (a bit on each crate, for example)
- [ ] Create a workflow that runs example snippets in the book (have at least one example).
