### ISSUE TITLE
feat(learner): allow database query into abstract

### ISSUE THREAD

**Issue by Autoparallel** [Autoparallel/learner#97]
## Tasks
- [ ] Rename `abstract_text` in SQL to `abstract`
- [ ] Allow FTS into `abstract`
- [ ] Start versioning the DB
